ktor {
  deployment {
    port = 8080
    watch = [ classes ]
  }
  application {
    modules = [ ru.hwaarn.booru.ApplicationKt.module ]
  }
}
app {
  database {
    url = ${?DATABASE_URL}
    user = ${?DATABASE_USER}
    password = ${?DATABASE_PASSWORD}
    maximumPoolSize = 10
  }
  security {
    issuer = "booru-backend"
    audience = "booru-mobile-client"
    realm = "booru-api"
    jwtSecret = ${?JWT_SECRET}
    accessTokenTtlMinutes = 60
    refreshTokenTtlDays = 30
  }
  storage {
    uploadRoot = ${?UPLOAD_ROOT}
    publicBaseUrl = ${?PUBLIC_BASE_URL}
  }
  moderation {
    autoApproveMembers = ${?AUTO_APPROVE_MEMBERS}
  }
}
